version: '2'
services:
  service_openresty_site:
    image: registry.cn-hangzhou.aliyuncs.com/liwmj/service_openresty_site:latest
    container_name: service_openresty_site
    privileged: true
    restart: unless-stopped
    volumes:
      - /persistent_data/com/liwmj/nginx/logs:/com/liwmj/nginx/logs
      - /persistent_data/com/liwmj/nginx/certs:/com/liwmj/nginx/certs
      - /persistent_data/com/liwmj/nginx/conf/services:/com/liwmj/nginx/conf/services
    network_mode: host
    dns:
      - 114.114.114.114
      - 8.8.8.8
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    depends_on:
      - redis
      - consul
  redis:
    image: "redis:5.0"
    container_name: redis
    restart: unless-stopped
    volumes:
      - /persistent_data/com/liwmj/redis/data:/data
    network_mode: host
    dns:
      - 114.114.114.114
      - 8.8.8.8
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
  consul:
    image: consul:latest
    container_name: consul
    restart: unless-stopped
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_CONFIG_DIR: /etc/consul
      CONSUL_DATA_DIR: /var/lib/consul
    command: agent -server -bootstrap-expect=1 -node=node1 -client 0.0.0.0 -ui
    volumes:
      - /persistent_data/com/liwmj/consul/config:/etc/consul
      - /persistent_data/com/liwmj/consul/data:/var/lib/consul
    network_mode: host
    dns:
      - 114.114.114.114
      - 8.8.8.8
    ports:
      - 127.0.0.1:8300:8300
      - 127.0.0.1:8400:8400
      - 127.0.0.1:8500:8500
      - 127.0.0.1:8600:8600
  webide:
    image: webide/webide:latest
    container_name: webide
    restart: unless-stopped
    volumes:
      - /persistent_data/com/liwmj/webide/.coding-ide:/root/.coding-ide
    network_mode: host
    dns:
      - 114.114.114.114
      - 8.8.8.8
    ports:
      - 127.0.0.1:8080:8080
  intellij-idea-license-server:
    image: registry.cn-hangzhou.aliyuncs.com/liwmj/intellij-idea-license-server:latest
    container_name: intellij-idea-license-server
    restart: unless-stopped
    network_mode: host
    dns:
      - 114.114.114.114
      - 8.8.8.8
    ports:
      - 127.0.0.1:1027:1027
  asciiflow:
    image: registry.cn-hangzhou.aliyuncs.com/liwmj/asciiflow:latest
    container_name: asciiflow
    restart: unless-stopped
    network_mode: host
    dns:
      - 114.114.114.114
      - 8.8.8.8
    ports:
      - 127.0.0.1:10100:10100
